name: Crow Integration

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to integrate Crow into"
        required: true
        default: "main"

jobs:
  crow-integrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Trigger Crow Agent
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.inputs.branch }}
          CROW_TOKEN: ${{ secrets.CROW_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: |
          RESPONSE=$(curl -s -X POST "https://URL_NEEDED_HERE/agent/trigger" \
            -H "Content-Type: application/json" \
            -d "{
              \"repo\": \"$REPO\",
              \"branch\": \"$BRANCH\",
              \"github_token\": \"$CROW_TOKEN\",
              \"run_id\": \"$RUN_ID\"
            }")
          echo "Response: $RESPONSE"